### ISSUE TITLE
On Firefox, event forms don't have a datepicker

### ISSUE THREAD

**Issue by robmcl4** [rit-sse/OneRepoToRuleThemAll#159] opened 2017-12-11 19:12 UTC
Using Firefox 57.0 (64-bit) on Windows, I expected the event submission to have a datepicker, but it doesn't.

![image](https://user-images.githubusercontent.com/884115/33848948-231e31ca-de7d-11e7-8c68-16112701de8c.png)

**Comment by vuzDylan** [comment] 2017-12-11 21:06
This is because firefox doesn't implement the HTML5 spec this is a dupe of using a real datepicker

**Closed** 2018-01-15 00:28 UTC
Labels: Events
