### ISSUE TITLE
GTV upcoming event screen blank after first pass through

### ISSUE THREAD

**Issue by akath20** [rit-sse/OneRepoToRuleThemAll#235] opened 2018-10-19 03:21 UTC
Leave the GTV on and rotate through once. The Upcoming Events screen will be blank.

**Comment by BenAlderfer** [comment] 2019-09-07 04:34
Duplicate of https://github.com/rit-sse/OneRepoToRuleThemAll/issues/171

**Closed by BenAlderfer** 2019-09-07 04:34 UTC
Labels: GTV
